Add license headers and check
Signed-off-by: Christopher Crone <christopher.crone@docker.com>

diff --git a/scripts/validate/fileheader b/scripts/validate/fileheader
--- a/scripts/validate/fileheader
+++ b/scripts/validate/fileheader
@@ -1,4 +1,6 @@
-#   Copyright 2020 The Compose Specification Authors.
+#!/usr/bin/env bash
+
+#   Copyright The Compose Specification Authors.
 
 #   Licensed under the Apache License, Version 2.0 (the "License");
 #   you may not use this file except in compliance with the License.
@@ -12,13 +14,15 @@
 #   See the License for the specific language governing permissions and
 #   limitations under the License.
 
-FROM golang:1.14
 
-WORKDIR /go/src/github.com/compose-spec/compose-ref
+set -eu -o pipefail
 
-ARG GOLANGCILINT_VERSION=v1.23.8
-RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCILINT_VERSION}
-RUN go get -u github.com/kunalkushwaha/ltag
+if ! command -v ltag; then
+    >&2 echo "ERROR: ltag not found. Install with:"
+    >&2 echo "    go get -u github.com/kunalkushwaha/ltag"
+    exit 1
+fi
 
-ENV GOFLAGS=-mod=vendor
-COPY . .
+BASEPATH="${1-}"
+
+ltag -t "${BASEPATH}scripts/validate/template" --excludes "validate vendor" --check -v
